### DISCUSSION TITLE
Delete after played

### DISCUSSION THREAD

**Discussion by X-static** [rfsbraz/deleterr#45] [Q&A] [answered]
Hi, if I wish to delete an episode of a movie a few days after being played, there's no option for that, isn't it?
Will `last_watched_threshold: 0` delete anything?

Thank you.

**Comment by rfsbraz** [comment]
Hi! You're right, there is currently no option for that but I think this is a valid use case. Creating an issue (#48) to track it and I'll implement this soon!

**Reply by rfsbraz** [reply]
Actually, wait.

`last_watched_threshold: X` - Prevents media watched in the last X days from being deleted. So this will fit your exact use case. Just set to let's say 4 days. This means that 4 days after you watched a certain movie, it will be elligible to be deleted (unless other rule filters it out)

**Reply by rfsbraz** [reply]
Issue then becomes that this deletes both watched and unwatched media, and I guess you wanted to only delete stuff you watched already?

I guess the solution would be to add a `watch_status` filter maybe, so it would become:

```
libraries:
   - name: "Movies"
      action_mode: "delete"
      last_watched_threshold: 5 # Keep movies watched in the last 5 days
      watch_status: watched # only delete things watched already
      radarr: Radarr
```
