### ISSUE TITLE
Library Tag Exclusion not working

### ISSUE THREAD

**Issue by mlamoure** [rfsbraz/deleterr#30]
I do not believe the tag exclusion is working for libraries, if I understand how it's supposed to work.  I set up a tag in both Sonarr and Radarr for "never_expire" and added that to the Deleterr config.  However a dry-run showed that it would have deleted several movies and shows that are tagged with this tag.

**Comment by rfsbraz** [comment]
Yeah I honestly expected this one to cause confusion. Every metadata aspect is checked against plex, I think `tags` are actually called `labels` there. But regardless these settings need to be clearer, and maybe more broad. I could do:

```yaml
libraries:
  - name: "Movies"
    ...
    exclude:
      plex:
        titles: ["Forrest Gump"]
        tags: ["children", "favorite"]
        genres: ["horror", "thriller"]
        collections: ["Marvel Cinematic Universe"]
        actors: ["Tom Cruise", "Brad Pitt"]
        producers: ["Steven Spielberg"]
        directors: ["Makoto Shinkai"]
        writers: ["Hayao Miyazaki"]
        studios: ["Studio Ghibli"]
        release_years: 5
      radarr:
        tags: ["some tag"]
        languages: ["en", "pt"]
        profiles: ["1080p"]
      trakt:
        max_items_per_list: 200
        lists:
          [
            "https://trakt.tv/movies/trending",
            "https://trakt.tv/movies/popular",
            "https://trakt.tv/movies/watched/yearly",
            "https://trakt.tv/movies/collected/yearly",
            "https://trakt.tv/users/justin/lists/imdb-top-rated-movies"
          ]
```

What do you think? It's way more robust but I'm afraid the overlapping settings could cause some confusion.

Another alternative is to check each field against every field that possible maps on each provider, but that makes what is happening way less obvious.
