### ISSUE TITLE
Add verbose mode - dry run produces no logs

### ISSUE THREAD

**Issue by jamo89** [rfsbraz/deleterr#33]
first time user 
setup my confutation file 
have dry run still enabled 
when I run this is all that I get:

2023-09-14 20:03:45 - INFO    :: config.py :: deleterr : Running in dry-run mode, no changes will be made.
2023-09-14 20:03:45 - INFO    :: deleterr.py :: deleterr : Processing sonarr instance: 'Sonarr'
2023-09-14 20:03:46 - INFO    :: deleterr.py :: deleterr : Processing radarr instance: 'Radarr'

I was assuming that media to be deleted would be found in this same log file. Is that accurate? 
Thanks

**Comment by rfsbraz** [comment]
That's probably because none of your media matched your conditions, otherwise they would have been printed. Try running it with the environment variable `LOG_LEVEL` set to `DEBUG`, that will print the reason why your media was not deleted for each entry.

If you're using docker compose this is how you do it:

```yaml
version: "3.9"
services:
    deleterr:
        image: ghcr.io/rfsbraz/deleterr:master
        container_name: deleterr
        environment:
            LOG_LEVEL: DEBUG
```
