### ISSUE TITLE
Delete after played

### ISSUE THREAD

**Issue by rfsbraz** [rfsbraz/deleterr#48]
### Discussed in https://github.com/rfsbraz/deleterr/discussions/45

<div type='discussions-op-text'>

<sup>Originally posted by **X-static** November 20, 2023</sup>
Hi, if I wish to delete an episode of a movie a few days after being played, there's no option for that, isn't it?
Will `last_watched_threshold: 0` delete anything?

Thank you.</div>

Add support for deleting media X days after being played

**Comment by rfsbraz** [comment]
`v0.1.0-beta` (`deleterr:v0.1.0-beta`) up with `watch_status` support, give it a go!

Sample config that deletes movies immediatelly after being watched:

```yaml
 - name: "Movies"
    action_mode: "delete"
    last_watched_threshold: 0
    watch_status: watched
    radarr: Radarr
```

Use in combination with `last_watched_threshold` to delete X days after watching
