### ISSUE TITLE
ability to exclude shows that the current season hasnt ended yet and then delete hwhole season after x days

### ISSUE THREAD

**Issue by nmbrg** [rfsbraz/deleterr#64]
would like to have the ability to hade deleterr exclude seasons from a tv shows that is currently not finished and only then start counting the "x amount of days until delete".

so as an example, if tv show is currently airing season 5. nothing should get deleted from that season as long as that season is still going on. only after that season is completed (last episode) it should start counting down "x amount of days until delete", and it should calculcate those days from the LAST episode of that season, and when met, delelete that whole season.

**Comment by rfsbraz** [comment]
This feature is already supported via the `exclude.sonarr.status` configuration option.

To exclude shows that are currently airing (where the current season hasn't ended yet), add this to your library config:

```yaml
libraries:
  - name: "TV Shows"
    sonarr: "Sonarr"
    exclude:
      sonarr:
        status: ["continuing"]  # Excludes shows that are still airing
```

Sonarr marks shows as `continuing` when they're actively airing new episodes, and `ended` when the series has concluded. This ensures that only completed shows are considered for deletion.

See the [Sonarr Exclusions documentation](https://rfsbraz.github.io/deleterr/CONFIGURATION#sonarr-exclusions) for more details.
